networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './nginx/html/413.html:/var/www/html/413.html'
      - media_volume:/app/media
    depends_on:
      - backend
    networks:
      - dev


  backend:
    build: .
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - dev
    volumes:
      - media_volume:/app/media
    depends_on:
      - db


  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - dev

volumes:
  media_volume: